# Generated by Django 5.1.15 on 2026-09-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.PositiveIntegerField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Аудит",
                "verbose_name_plural": "Аудит",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="Дата и время ЛР")),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Записан"),
                            ("NO_SHOW", "Неявка"),
                            ("CANCELLED", "Отменил запись"),
                            ("SLOT_CANCELLED", "Слот отменён"),
                            ("REACCESS", "Повторный доступ"),
                            ("VISITED", "Посетил"),
                        ],
                        default="BOOKED",
                        help_text="Текущее состояние строки записи.",
                        max_length=16,
                    ),
                ),
                (
                    "had_no_show",
                    models.BooleanField(
                        default=False,
                        help_text="Факт засчитанной неявки (слой 2): ставится при первом NO_SHOW, сохраняется после REACCESS, снимается только исправлением NO_SHOW → VISITED. Нужен для отчётов и аналитики.",
                        verbose_name="Была неявка",
                    ),
                ),
                (
                    "cancel_source",
                    models.CharField(
                        blank=True,
                        choices=[("STUDENT", "Студент"), ("STAFF", "Сотрудник")],
                        help_text="Заполняется только для статуса CANCELLED: студент или сотрудник.",
                        max_length=16,
                        null=True,
                        verbose_name="Кто отменил запись",
                    ),
                ),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("AUTO", "Автоматическая"),
                            ("MANUAL", "Не автоматическая"),
                        ],
                        default="AUTO",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Записан"),
                            ("NO_SHOW", "Неявка"),
                            ("CANCELLED", "Отменил запись"),
                            ("SLOT_CANCELLED", "Слот отменён"),
                            ("REACCESS", "Повторный доступ"),
                            ("VISITED", "Посетил"),
                        ],
                        max_length=16,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда студент просмотрел уведомление об изменении статуса.",
                        null=True,
                        verbose_name="Просмотрено студентом",
                    ),
                ),
            ],
            options={
                "verbose_name": "История статуса",
                "verbose_name_plural": "История статусов",
                "ordering": ["changed_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentLabAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no_show_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Сколько раз студенту ставили неявку в этой лаборатории (сохраняется для аналитики).",
                        verbose_name="Количество неявок",
                    ),
                ),
                (
                    "explanation_required",
                    models.BooleanField(
                        default=False,
                        help_text="True при 3+ неявках в этой лаборатории. Снимается сотрудником после получения объяснительной; счётчик неявок при этом не сбрасывается.",
                        verbose_name="Требуется объяснительная",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Посещаемость по лаборатории",
                "verbose_name_plural": "Посещаемость по лабораториям",
            },
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=256)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Открыт"),
                            ("IN_PROGRESS", "В работе"),
                            ("RESOLVED", "Отвечено"),
                            ("CLOSED", "Закрыт"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Очередь",
                "verbose_name_plural": "Очередь",
                "ordering": ["position"],
            },
        ),
    ]
