# Generated by Django 5.1.15 on 2026-09-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="cancel_source",
            field=models.CharField(
                blank=True,
                choices=[("STUDENT", "Студент"), ("STAFF", "Сотрудник")],
                max_length=16,
                null=True,
                verbose_name="Кто отменил запись",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Записан"),
                    ("NO_SHOW", "Неявка"),
                    ("CANCELLED", "Отменил запись"),
                    ("SLOT_CANCELLED", "Слот отменён"),
                    ("REACCESS", "Повторный доступ"),
                    ("VISITED", "Посетил"),
                ],
                default="BOOKED",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="had_no_show",
            field=models.BooleanField(
                default=False,
                help_text="Факт неявки: ставится при первом NO_SHOW, переживает REACCESS, снимается исправлением NO_SHOW → VISITED.",
                verbose_name="Была неявка",
            ),
        ),
        migrations.AlterField(
            model_name="bookingstatushistory",
            name="acknowledged_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Просмотрено студентом"
            ),
        ),
        migrations.AlterField(
            model_name="studentlabattendance",
            name="explanation_required",
            field=models.BooleanField(
                default=False,
                help_text="True при 3+ неявках; снимается сотрудником, счётчик сохраняется.",
                verbose_name="Требуется объяснительная",
            ),
        ),
        migrations.AlterField(
            model_name="studentlabattendance",
            name="no_show_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество неявок"
            ),
        ),
    ]
