# Generated by Django 5.1.15 on 2026-09-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_cancel_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="staff_read_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Прочитано сотрудником"
            ),
        ),
    ]
