# Generated by Django 5.1.15 on 2026-09-04 11:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Короткий код"
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Кафедра",
                "verbose_name_plural": "Кафедры",
                "ordering": ["ordering", "title"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=16, unique=True, verbose_name="Код"),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "ordering",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Факультет",
                "verbose_name_plural": "Факультеты",
                "ordering": ["ordering", "title"],
            },
        ),
        migrations.CreateModel(
            name="GroupDisciplineLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("IMPORTED_WORKLOAD", "Импорт нагрузки"),
                            ("MANUAL_ADJUSTMENT", "Ручная корректировка"),
                        ],
                        default="IMPORTED_WORKLOAD",
                        max_length=32,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "import_batch_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Пакет импорта"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Нагрузка группы по дисциплине",
                "verbose_name_plural": "Нагрузка групп по дисциплинам",
                "ordering": ["group__name", "discipline__title"],
            },
        ),
        migrations.CreateModel(
            name="GroupLabWorkOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("OPEN", "Открыть"), ("HIDDEN", "Скрыть")],
                        max_length=16,
                        verbose_name="Режим",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Причина"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Исключение по ЛР для группы",
                "verbose_name_plural": "Исключения по ЛР для групп",
            },
        ),
        migrations.CreateModel(
            name="LabWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=1, verbose_name="Номер"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Код ЛР"
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        choices=[
                            (30, "30 мин"),
                            (45, "45 мин"),
                            (60, "60 мин"),
                            (90, "90 мин"),
                        ],
                        default=90,
                        verbose_name="Длительность (мин)",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=30, verbose_name="Макс. мест"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
            ],
            options={
                "verbose_name": "Лабораторная работа",
                "verbose_name_plural": "Лабораторные работы",
                "ordering": ["number", "title"],
            },
        ),
        migrations.CreateModel(
            name="LabWorkMethodics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="methodics/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="PDF",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Название"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
            ],
            options={
                "verbose_name": "Методичка",
                "verbose_name_plural": "Методички",
                "ordering": ["uploaded_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активный"),
                ),
            ],
            options={
                "verbose_name": "Семестр",
                "verbose_name_plural": "Семестры",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="Группа"),
                ),
                (
                    "faculty",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Факультет"
                    ),
                ),
                (
                    "dekanat_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ID в Деканате"
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебная группа",
                "verbose_name_plural": "Учебные группы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=32, verbose_name="Код"),
                ),
                (
                    "short_code",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Короткий код"
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "dekanat_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ID в Деканате"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disciplines",
                        to="academics.department",
                        verbose_name="Кафедра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дисциплина",
                "verbose_name_plural": "Дисциплины",
                "ordering": ["title"],
            },
        ),
    ]
