# Generated by Django 5.1.15 on 2026-09-04 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipline",
            name="laboratories",
            field=models.ManyToManyField(
                blank=True,
                related_name="disciplines",
                through="scheduling.LabDisciplineBinding",
                to="scheduling.laboratory",
                verbose_name="Лаборатории",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="academics.faculty",
                verbose_name="Факультет",
            ),
        ),
        migrations.AddField(
            model_name="groupdisciplineload",
            name="discipline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_loads",
                to="academics.discipline",
                verbose_name="Дисциплина",
            ),
        ),
        migrations.AddField(
            model_name="labwork",
            name="default_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_lab_works",
                to="scheduling.room",
                verbose_name="Аудитория по умолчанию",
            ),
        ),
        migrations.AddField(
            model_name="labwork",
            name="disciplines",
            field=models.ManyToManyField(
                related_name="lab_works",
                to="academics.discipline",
                verbose_name="Дисциплины",
            ),
        ),
        migrations.AddField(
            model_name="labwork",
            name="laboratories",
            field=models.ManyToManyField(
                blank=True,
                related_name="lab_works",
                to="scheduling.laboratory",
                verbose_name="Лаборатории",
            ),
        ),
        migrations.AddField(
            model_name="labwork",
            name="primary_stand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_for_lab_works",
                to="scheduling.labstand",
                verbose_name="Основной стенд",
            ),
        ),
        migrations.AddField(
            model_name="labwork",
            name="training_centers",
            field=models.ManyToManyField(
                blank=True,
                related_name="lab_works",
                to="scheduling.trainingcenter",
                verbose_name="Учебные центры",
            ),
        ),
        migrations.AddField(
            model_name="grouplabworkoverride",
            name="lab_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_overrides",
                to="academics.labwork",
                verbose_name="Лабораторная работа",
            ),
        ),
        migrations.AddField(
            model_name="labworkmethodics",
            name="lab_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="methodics_files",
                to="academics.labwork",
                verbose_name="Лабораторная работа",
            ),
        ),
        migrations.AddField(
            model_name="grouplabworkoverride",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_lab_work_overrides",
                to="academics.semester",
                verbose_name="Семестр",
            ),
        ),
        migrations.AddField(
            model_name="groupdisciplineload",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_discipline_loads",
                to="academics.semester",
                verbose_name="Семестр",
            ),
        ),
        migrations.AddField(
            model_name="discipline",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplines",
                to="academics.semester",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_groups",
                to="academics.department",
                verbose_name="Кафедра",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="disciplines",
            field=models.ManyToManyField(
                blank=True,
                related_name="student_groups",
                to="academics.discipline",
                verbose_name="Дисциплины учебного плана",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="lab_works",
            field=models.ManyToManyField(
                blank=True,
                related_name="student_groups",
                to="academics.labwork",
                verbose_name="Лабораторные работы учебного плана",
            ),
        ),
        migrations.AddField(
            model_name="grouplabworkoverride",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_work_overrides",
                to="academics.studentgroup",
                verbose_name="Учебная группа",
            ),
        ),
        migrations.AddField(
            model_name="groupdisciplineload",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discipline_loads",
                to="academics.studentgroup",
                verbose_name="Учебная группа",
            ),
        ),
        migrations.AddConstraint(
            model_name="labwork",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__in", (30, 45, 60, 90))),
                name="academics_labwork_allowed_duration",
            ),
        ),
        migrations.AddConstraint(
            model_name="labwork",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__isnull", False)),
                fields=("code",),
                name="academics_labwork_code_unique_not_null",
            ),
        ),
        migrations.AddIndex(
            model_name="grouplabworkoverride",
            index=models.Index(
                fields=["semester", "is_active"], name="academics_g_semeste_fc6a99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grouplabworkoverride",
            index=models.Index(
                fields=["group", "semester"], name="academics_g_group_i_fe07be_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="grouplabworkoverride",
            constraint=models.UniqueConstraint(
                fields=("group", "semester", "lab_work"),
                name="academics_group_lab_work_override_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="groupdisciplineload",
            index=models.Index(
                fields=["semester", "is_active"], name="academics_g_semeste_e7a0d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupdisciplineload",
            index=models.Index(
                fields=["group", "semester"], name="academics_g_group_i_598af5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupdisciplineload",
            index=models.Index(
                fields=["discipline", "semester"], name="academics_g_discipl_339464_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupdisciplineload",
            constraint=models.UniqueConstraint(
                fields=("group", "semester", "discipline"),
                name="academics_group_discipline_load_unique",
            ),
        ),
    ]
