# Generated by Django 5.1.15 on 2026-09-04 11:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Праздничный день",
                "verbose_name_plural": "Праздничные дни",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="LabDisciplineBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_override",
                    models.BooleanField(
                        default=False, verbose_name="Несоответствующая привязка"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Причина"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Привязка дисциплины к лаборатории",
                "verbose_name_plural": "Привязки дисциплин к лабораториям",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Краткое название"
                    ),
                ),
                (
                    "lab_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Кафедральная"),
                            ("INTERDEPT", "Межкафедральная"),
                            ("COMPLEX", "Комплексная"),
                        ],
                        default="REGULAR",
                        max_length=16,
                        verbose_name="Тип лаборатории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лаборатория",
                "verbose_name_plural": "Лаборатории",
                "ordering": ["training_center", "name"],
            },
        ),
        migrations.CreateModel(
            name="LaboratoryBookingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_horizon_days",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Горизонт записи (дни)"
                    ),
                ),
                (
                    "booking_day_opens_at",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Открытие нового дня"
                    ),
                ),
                (
                    "booking_day_closes_at",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Закрытие ближнего дня"
                    ),
                ),
                (
                    "booking_cancel_hours",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Отмена за N часов"
                    ),
                ),
                (
                    "restriction_base_time",
                    models.TimeField(
                        default=datetime.time(9, 0),
                        verbose_name="Базовое время ограничения",
                    ),
                ),
                (
                    "restriction_hours_before_base",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="NULL = ограничение отсутствует",
                        null=True,
                        verbose_name="Ограничение записи за N часов до базового времени",
                    ),
                ),
                (
                    "auto_visited_mode",
                    models.CharField(
                        choices=[
                            ("MANUAL", "отсутствует"),
                            ("AT_22_00", "В 22:00 текущего дня"),
                            ("AT_09_00_NEXT", "В 9:00 следующего дня"),
                        ],
                        default="MANUAL",
                        max_length=16,
                        verbose_name="Автопроставление «Посетил»",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки записи лаборатории",
                "verbose_name_plural": "Настройки записи лабораторий",
            },
        ),
        migrations.CreateModel(
            name="LabSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Начало")),
                ("ends_at", models.DateTimeField(verbose_name="Окончание")),
                ("capacity", models.PositiveIntegerField(verbose_name="Мест")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("OPEN", "Открыта"),
                            ("CLOSED", "Закрыта"),
                            ("CANCELLED", "Отменена"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот лабораторной",
                "verbose_name_plural": "Слоты лабораторных",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="LabStand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Наименование")),
                (
                    "inventory_number",
                    models.CharField(max_length=64, verbose_name="Инвентарный номер"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="stands/", verbose_name="Фотография"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
            ],
            options={
                "verbose_name": "Лабораторный стенд",
                "verbose_name_plural": "Лабораторные стенды",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=32, verbose_name="Аудитория №")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Название"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="rooms/", verbose_name="Фотография"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=30, verbose_name="Вместимость"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="Заблокирована"),
                ),
            ],
            options={
                "verbose_name": "Аудитория",
                "verbose_name_plural": "Аудитории",
            },
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duty_role",
                    models.CharField(
                        choices=[
                            ("LAB_STAFF_DUTY", "Дежурство сотрудника лаборатории"),
                            ("TEACHER_DUTY", "Дежурство преподавателя"),
                            ("OTHER", "Другое"),
                        ],
                        default="LAB_STAFF_DUTY",
                        max_length=32,
                        verbose_name="Тип дежурства",
                    ),
                ),
                (
                    "week_parity",
                    models.CharField(
                        choices=[
                            ("ODD", "Нечётная"),
                            ("EVEN", "Чётная"),
                            ("BOTH", "Каждую неделю"),
                        ],
                        default="BOTH",
                        max_length=8,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(verbose_name="День недели (0=Пн)"),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        choices=[
                            (30, "30 мин"),
                            (45, "45 мин"),
                            (60, "60 мин"),
                            (90, "90 мин"),
                        ],
                        default=90,
                        verbose_name="Длительность (мин)",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=30, verbose_name="Мест"),
                ),
                (
                    "load_group_label",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Группа по нагрузке"
                    ),
                ),
                (
                    "manual_title",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Ручное описание"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Запись расписания",
                "verbose_name_plural": "Расписание",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleEntryDisciplineSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дисциплина слота расписания",
                "verbose_name_plural": "Дисциплины слотов расписания",
            },
        ),
        migrations.CreateModel(
            name="TrainingCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(unique=True, verbose_name="УЦ №"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный центр",
                "verbose_name_plural": "Учебные центры",
            },
        ),
    ]
