# Generated by Django 5.1.15 on 2026-09-08 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
        ("scheduling", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_excluded_from_autogen",
            field=models.BooleanField(
                default=False, verbose_name="Исключена из автогенерации слотов"
            ),
        ),
        migrations.AddConstraint(
            model_name="labsession",
            constraint=models.UniqueConstraint(
                fields=("lab_work", "room", "semester", "starts_at"),
                name="scheduling_labsession_unique_slot",
            ),
        ),
    ]
